// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9kfySseQf6-us7s0fkby8RHzh4nn7lwk',
    appId: '1:436650959137:web:e799e105ca69a450d79e60',
    messagingSenderId: '436650959137',
    projectId: 'book-app-61d3e',
    authDomain: 'book-app-61d3e.firebaseapp.com',
    storageBucket: 'book-app-61d3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmwtUwZG7ACMp6jIfgxk0ps7myqK2berw',
    appId: '1:436650959137:android:c75a8fb65771e57ad79e60',
    messagingSenderId: '436650959137',
    projectId: 'book-app-61d3e',
    storageBucket: 'book-app-61d3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYfR2Q9rRAAZAeVByKZIMG8aYBZKCq_bA',
    appId: '1:436650959137:ios:e73240b7d945b1ddd79e60',
    messagingSenderId: '436650959137',
    projectId: 'book-app-61d3e',
    storageBucket: 'book-app-61d3e.appspot.com',
    iosClientId: '436650959137-a2on547ke18husu3iud1jmbvcvhh248h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYfR2Q9rRAAZAeVByKZIMG8aYBZKCq_bA',
    appId: '1:436650959137:ios:e73240b7d945b1ddd79e60',
    messagingSenderId: '436650959137',
    projectId: 'book-app-61d3e',
    storageBucket: 'book-app-61d3e.appspot.com',
    iosClientId: '436650959137-a2on547ke18husu3iud1jmbvcvhh248h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp',
  );
}
